### ISSUE TITLE
Ports not binding on Linux or Windows Server 2019

### ISSUE THREAD

**Issue by ijarofjami** [tiltedphoques/TiltedEvolution#310]
After following the instructions for both linux and Windows on the wiki, ports will not bind.  This is not a port forwarding issue, as I can't locally query the port either.

**Comment by androbourne** [comment]
This is a port forwarding issue and not likely to be an issue with the reborn mod.

Make sure you are port forwarding the proper server port in your route and local OS firewall. OS firewall both on Linux and Windows need to have exceptions for the server port.

**Comment by ijarofjami** [comment]
I've completely disabled the firewall on both Windows and the Ubuntu machine just to eliminate that as being a problem. Additionally, other game servers that I'm hosting have port forwarding working on the same machines. I checked the services running using netstat and ss and neither are showing the server bound to the port.

**Comment by androbourne** [comment]
> I've completely disabled the firewall on both Windows and the Ubuntu machine just to eliminate that as being a problem. Additionally, other game servers that I'm hosting have port forwarding working on the same machines. I checked the services running using netstat and ss and neither are showing the server bound to the port.

I could see it being an issue with the docker image, but many people are running it on Windows and it binds ports just fine. You said both on Windows and Linux. I and many others host our own servers on Windows and it's working just fine. I've seen several complaints about the docker image though.

Have you tried running on it on Windows machine and using procmon to see what's going on with it? At the very least it should work there, if it doesn't then clearly something on your port forwarding or local system is blocking it from going out. Also check your firewall logs and maybe try another server port for reborn.

**Comment by RobbeBryssinck** [comment]
This is a local configuration issue, the docker image works just fine.

**Comment by ijarofjami** [comment]
> I could see it being an issue with the docker image, but many people are running it on Windows and it binds ports just fine. You said both on Windows and Linux. I and many others host our own servers on Windows and it's working just fine. I've seen several complaints about the docker image though.

Have you tried running on it on Windows machine and using procmon to see what's going on with it? At the very least it should work there, if it doesn't then clearly something on your port forwarding, network or local system is blocking it from going out. Also check your firewall logs and maybe try another server port for reborn.

Also disabling the firewall on windows doesn't stop it from blocking. Make port exceptions, don't disable it.

I haven't run procmon yet, but I have confirmed that Skyrim Together Reborn server isn't binding to the port whatsoever using netstat.  I'm not sure why it's not, though.  While I don't agree with the statement that turning off the firewall won't stop blocking stuff, I've also created the port exceptions.  Regardless, that doesn't explain why server isn't binding to the port (on either Ubuntu or Windows.)



> This is a local configuration issue, the docker image works just fine.
It's not just docker, it's also happening in Windows.  It's a brand new ubuntu instance installed from the ISO specifically for the Skyrim Together Reborn server and I literally copied all of the commands from the Wiki tutorial just to eliminate it being human error on my end.

**Comment by androbourne** [comment]
> 

Firsty, netstat shows running services and their ports. Doesn't verify "binding" You have yet to share your netstats results but im assuming its showing the server running with no port assigned? As I stated above that could indicate a port conflict which is why I stated "try changing the default server port" as in changing it in the config file to another port....

Secondly Reborn has been out for over 5 days and not a single person other than you has sent in this "error". If it was really a problem there would be WAY more reports about this. There isn't a single one other than what we find on discord which 99% of the time is someone that is not port forwarding correctly or has an incorrect config on their local system.

Thirdly, you can disagree about Windows Firewall being turned off and still blocking ports all you want. I'm a network/system engineer who has been in the field for over 15 years I know this as a fact from my own experience but you dont want to trust that, a simple google search of "windows firewall keeps blocking even after being turned off" will result in many searches like this one. 

https://www.fileinspect.com/blog/stop-windows-10-firewall-blocking-apps-when-being-disabled/#:~:text=Disable%20Third%2DParty%20Antivirus%20or%20Firewall%20Software&text=These%20system%20protection%20tools%20might,and%20check%20if%20that%20helps.

So like I said earlier, without a doubt if it is happening on both Windows and Linux it is 100% no way its not a local configuration issue. 100s of people are using it in both OS's and yet you are the only one stating this error.

**Comment by androbourne** [comment]
> > I could see it being an issue with the docker image, but many people are running it on Windows and it binds ports just fine.
> > You said both on Windows and Linux. I and many others host our own servers on Windows and it's working just fine. I've seen several complaints about the docker image though.
> 
> > Have you tried running on it on Windows machine and using procmon to see what's going on with it? At the very least it should work there, if it doesn't then clearly something on your port forwarding, network or local system is blocking it from going out. Also check your firewall logs and maybe try another server port for reborn.
> 
> > Also disabling the firewall on windows doesn't stop it from blocking. Make port exceptions, don't disable it.
> 
> I haven't run procmon yet, but I have confirmed that Skyrim Together Reborn server isn't binding to the port whatsoever using netstat. I'm not sure why it's not, though. While I don't agree with the statement that turning off the firewall won't stop blocking stuff, I've also created the port exceptions. Regardless, that doesn't explain why server isn't binding to the port (on either Ubuntu or Windows.)
> 
> > This is a local configuration issue, the docker image works just fine.
> 
> It's not just docker, it's also happening in Windows. It's a brand new ubuntu instance installed from the ISO specifically for the Skyrim Together Reborn server and I literally copied all of the commands from the Wiki tutorial just to eliminate it being human error on my end.

Firsty, netstat shows running services and their ports. Doesn't verify "binding" You have yet to share your netstats results but im assuming its showing the server running with no port assigned? As I stated above that could indicate a port conflict which is why I stated "try changing the default server port" as in changing it in the config file to another port....

Secondly Reborn has been out for over 5 days and not a single person other than you has sent in this "error". If it was really a problem there would be WAY more reports about this. There isn't a single one other than what we find on discord which 99% of the time is someone that is not port forwarding correctly or has an incorrect config on their local system.

Thirdly, you can disagree about Windows Firewall being turned off and still blocking ports all you want. I'm a network/system engineer who has been in the field for over 15 years I know this as a fact from my own experience but you dont want to trust that, a simple google search of "windows firewall keeps blocking even after being turned off" will result in many searches like this one.

https://www.fileinspect.com/blog/stop-windows-10-firewall-blocking-apps-when-being-disabled/#:~:text=Disable%20Third%2DParty%20Antivirus%20or%20Firewall%20Software&text=These%20system%20protection%20tools%20might,and%20check%20if%20that%20helps.

So like I said earlier, without a doubt if it is happening on both Windows and Linux it is 100% no way its not a local configuration issue. 100s of people are using it in both OS's and yet you are the only one stating this error.

**Comment by ijarofjami** [comment]
> Firsty, netstat shows running services and their ports. Doesn't verify "binding" You have yet to share your netstats results but im assuming its showing the server running with no port assigned? As I stated above that could indicate a port conflict which is why I stated "try changing the default server port" as in changing it in the config file to another port....

That's exactly what netstat does.  Like I said.  It doesn't show the server running at all, as it only shows services that are bound to ports.  There are no other services running on the same port.

> Thirdly, you can disagree about Windows Firewall being turned off and still blocking ports all you want. I'm a network/system engineer who has been in the field for over 15 years I know this as a fact from my own experience but you dont want to trust that, a simple google search of "windows firewall keeps blocking even after being turned off" will result in many searches like this one.

That's fine that you work there, I also work in IT and have not had any issues like this with other game servers (or any non-game servers for that matter).  The link that you shared is literally saying to stop windows firewall from blocking is by turning off windows firewall.  So, that's a really bad point.

If it's a local configuration problem, then it's a problem on the side of the wiki instructions as mentioned - brand new Ubuntu VM, copied and pasted commands, followed the instructions to a T.  Twice.  Same thing with the Windows instance.  Even tried two separate Windows instances just to be safe.  I don't know what to tell you, I just wanted to bring it to the attention of the devs.  If you don't want to do anything with it, that's fine.

**Comment by androbourne** [comment]
> > Firsty, netstat shows running services and their ports. Doesn't verify "binding" You have yet to share your netstats results but im assuming its showing the server running with no port assigned? As I stated above that could indicate a port conflict which is why I stated "try changing the default server port" as in changing it in the config file to another port....
> 
> That's exactly what netstat does. Like I said. It doesn't show the server running at all, as it only shows services that are bound to ports. There are no other services running on the same port.
> 
> > Thirdly, you can disagree about Windows Firewall being turned off and still blocking ports all you want. I'm a network/system engineer who has been in the field for over 15 years I know this as a fact from my own experience but you dont want to trust that, a simple google search of "windows firewall keeps blocking even after being turned off" will result in many searches like this one.
> 
> That's fine that you work there, I also work in IT and have not had any issues like this with other game servers (or any non-game servers for that matter). The link that you shared is literally saying to stop windows firewall from blocking is by turning off windows firewall. So, that's a really bad point.
> 
> If it's a local configuration problem, then it's a problem on the side of the wiki instructions as mentioned - brand new Ubuntu VM, copied and pasted commands, followed the instructions to a T. Twice. Same thing with the Windows instance. Even tried two separate Windows instances just to be safe. I don't know what to tell you, I just wanted to bring it to the attention of the devs. If you don't want to do anything with it, that's fine.

You do you. It's clearly a local configuration issue and with the facts presented above (aka 100s of other players using it and only you have reported the "problem"). And you say you work in IT but didn't even know about the local windows firewall still blocking ports when closed? It's a fairly common issue...

Anyways at this point, I suggest you look up installation videos for Reborn server setup on youtube instead of the WikI if you really feel that way. Wiki is fine and I've helped many others set up their own local servers using it. It was even recently updated to provide more detailed information since patch 1.1.

**Comment by ijarofjami** [comment]
> You do you. It's clearly a local configuration issue and with the facts presented above (aka 100s of other players using it and only you have reported the "problem"). And you say you work in IT but didn't even know about the local windows firewall still blocking ports when closed? It's a fairly common issue...

Like I showed you already, you were wrong about the ports and Windows Firewall.  So, your thinking that turning off firewall doesn't turn off Windows Firewall is a cute idea, but absolutely wrong.  Maybe try doing some research on what "turning off" means?  Even following those instructions (which is what I was already doing) didn't fix the problem.  As mentioned, the Reborn server isn't binding to the proper port.

> Anyways at this point, I suggest you look up installation videos for Reborn server setup on youtube instead of the WikI if you really feel that way. Wiki is fine and I've helped many others set up their own local servers using it. It was even recently updated to provide more detailed information since patch 1.1.

> Anyways at this point, I suggest you look up installation videos for Reborn server setup on youtube instead of the WikI if you really feel that way. Wiki is fine and I've helped many others set up their own local servers using it. It was even recently updated to provide more detailed information since patch 1.1.

At this point, my faith in this project is diminished to 0.  Even 1.1 tutorial doesn't lead me to have any faith in the project.  Especially with the way that this issue was handled.

**Comment by androbourne** [comment]
> > You do you. It's clearly a local configuration issue and with the facts presented above (aka 100s of other players using it and only you have reported the "problem"). And you say you work in IT but didn't even know about the local windows firewall still blocking ports when closed? It's a fairly common issue...
> 
> Like I showed you already, you were wrong about the ports and Windows Firewall. So, your thinking that turning off firewall doesn't turn off Windows Firewall is a cute idea, but absolutely wrong. Maybe try doing some research on what "turning off" means? Even following those instructions (which is what I was already doing) didn't fix the problem. As mentioned, the Reborn server isn't binding to the proper port.
> 
> > Anyways at this point, I suggest you look up installation videos for Reborn server setup on youtube instead of the WikI if you really feel that way. Wiki is fine and I've helped many others set up their own local servers using it. It was even recently updated to provide more detailed information since patch 1.1.
> 
> > Anyways at this point, I suggest you look up installation videos for Reborn server setup on youtube instead of the WikI if you really feel that way. Wiki is fine and I've helped many others set up their own local servers using it. It was even recently updated to provide more detailed information since patch 1.1.
> 
> At this point, my faith in this project is diminished to 0. Even 1.1 tutorial doesn't lead me to have any faith in the project. Especially with the way that this issue was handled.

Right, I presented facts that can easily be googled and you choose to ignore them. That's on you. Doesn't change the fact it is a known issue and has been for years with Windows Firewall. Anyone that actually works in IT knows this. So clearly it's not your profession.

I don't have faith in your technical skills yet where we are. Only you are complaining about something that obviously isn't a problem. You just lack the technical know-how to troubleshoot and resolve the issue properly.

If you provide me with remote access to your system. I'll have you up and running in under 10 minutes. I normally charge $150/hr but to prove the point I'll do it for free. I do suspect you will make up some reason to avoid this just to save face.

**Comment by ijarofjami** [comment]
I've completely disabled the firewall on both Windows and Linux. Other game
servers that I'm hosting have port forwarding working on the same machines.
I checked the services running using netstat and ss and neither are showing
the server bound to the port.
