### ISSUE TITLE
Player to Player Trading

### ISSUE THREAD

**Issue by EnoughReality** [tiltedphoques/TiltedEvolution#450]
Player to player trading

There is a mod caused use or take that enables the ability for you to shift while looking at an object and choose to use or take, would it be possible to implement something like that but for trading? in which you could look at a player and shift and then be given an option to request to trade, I think it would be far more immersive than doing something like /trade or putting it in a container nearby

Mod that I got the idea from:
https://www.nexusmods.com/skyrimspecialedition/mods/70868

**Comment by Thercious** [comment]
I had made [a suggestion one month ago](https://github.com/tiltedphoques/TiltedEvolution/issues/325), but it seems the "issue" to actually implement any trading system is with the current inventory system, which will require some work before a trading implementation becomes viable.

**Comment by Sturlen** [comment]
Using the mod [Better Speechcraft](https://www.nexusmods.com/skyrimspecialedition/mods/21296), you can gift items to other players. Because of this, I believe adding the ability give items through this mod should be doable, just depends on how you want to add it.
A full trading system might be a bit outside the scope of this mod though. If you can't trust your parter to deal honestly, how can you trust them not to spawn in 100 Alduins?
