### ISSUE TITLE
Failed to load Skyrim Address Library

### ISSUE THREAD

**Issue by Mehlordie** [tiltedphoques/TiltedEvolution#529]
Hello! I have the most recent Skyrim Special Addition for windows and I'm trying to load Skyrim Together Reborn v1.3.2 and Address library for SKSE Plugins - All in one (Anniversary Edition) v8.

I get an error that says: 
![d0cf85effa092f77b43fc3bd68062b0a](https://user-images.githubusercontent.com/34111832/196308017-77e2a441-a2ca-425e-9892-987573b3fe2a.png)

What should I do?

**Comment by ToeKneeRED** [comment]
You probably figured it out by now but just in case, double-check the directory it is looking for as you most likely didn't rename your C drive to D. Otherwise, check the troubleshooting page listed there and try out/check all things listed there. If you still haven't gotten it, ask in the questions channel in the discord.
