### ISSUE TITLE
Face bugged in STR when using modded followers or mods which change the appearance of npc's .

### ISSUE THREAD

**Issue by Gollum0002** [tiltedphoques/TiltedEvolution#624]
![1](https://github.com/tiltedphoques/TiltedEvolution/assets/109045152/86b680cd-93a6-4edd-92fa-fd03becf87fa)

This is an image of the follower mod Recorder taken in Skyrim together reborn.

![2](https://github.com/tiltedphoques/TiltedEvolution/assets/109045152/f72ba6a2-f112-4584-ae14-65cd6ae288c3)

This is an image of the same follower mod taken in skse64_loader.exe.

Not using any mods which may alter character appearances. Load order attached below.

[loadorder.txt](https://github.com/tiltedphoques/TiltedEvolution/files/12403227/loadorder.txt)

**Comment by Gollum0002** [comment]
I forgot to mention but this bug also affects vanilla npc's when their appearance in changed by other mods... 

For example, Bijin Wives, Bijin Npc's and Bijin Warmaidens. Their appearances does not match the ones shown on the Mod's page (FYI I have used these mods before so it is very easy to notice the difference)

**Comment by VENDETTA5** [comment]
Ah dude STR doesn't support mods. They say: Use any mods at your own risk.

I think they are 100% aware about this issue but they don't bother(Because vanilla works, bruh). Somehow the facegen is hardcoded in multiplayer due to how multiplayer syncs the stuff.

If someone makes a 100% nice working fork with good code and no downsides that fixes this 'issue' and they manage to successfully merge it with main branch then the issue could be fixed.

But otherwise I doubt any of the developers would bother considering that the vanilla game works fine. I don't use any mods that use facegen edits and everything works alright.

**Comment by ToeKneeRED** [comment]
The mod compatibility list is the issue list in its own repo. The link to it is also under "Helpful Links" on the wiki.
[https://github.com/tiltedphoques/Mod-Compatibility](https://github.com/tiltedphoques/Mod-Compatibility)
